import type { Metadata } from 'next'
import { Inter, Bebas_Neue } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import { ThemeProvider } from '@/src/Theme/ThemeProvider'
import { Header } from '@/src/feature/layout/Header'
import { Footer } from '@/src/feature/layout/Footer'

const inter = Inter({ subsets: ['latin'] })
const bebas = Bebas_Neue({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en" className="h-full">
         <body className={clsx(inter.className, 'bg-background h-full')}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
               <div className="flex flex-col h-full">
                  <Header  />
                  <div className="flex-1 max-w-lg m-auto py-12 w-full">
                     {children}
                  </div>
                  <Footer/>
               </div>
            </ThemeProvider>
         </body>
      </html>
   )
}
